"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from os import getenv
import logging.config
from django.conf.global_settings import LOGGING, INTERNAL_IPS, CACHES, CACHE_MIDDLEWARE_SECONDS
# from django.conf.global_settings import LOGIN_REDIRECT_URL, MEDIA_URL, MEDIA_ROOT, DEFAULT_FILE_STORAGE, USE_L10N, \
#     LOCALE_PATHS, LANGUAGES


from rest_framework.reverse import reverse_lazy

from django.utils.translation import gettext_lazy as _

import sentry_sdk



sentry_sdk.init(
    dsn="https://6bb6c8d5202cc5adb8a03dc95fe1a3bb@o4509162051534848.ingest.de.sentry.io/4510589292118097",
    # Add data like request headers and IP for users,
    # see https://docs.sentry.io/platforms/python/data-management/data-collected/ for more info
    send_default_pii=True,
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Путь к директории, где будет храниться база данных
DATABASE_DIR = BASE_DIR / "database"  # Создаём объект Path для папки 'database' внутри проекта

# Создаём папку для базы данных, если её ещё нет
DATABASE_DIR.mkdir(exist_ok=True)  # Если папка уже существует, ошибок не будет


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = getenv(
    "DJANGO_SECRET_KEY",
    'django-insecure-rw+)gw2)w8u6e_g8yp2o!2i#ond@9d6xd+5+s-lm#w-2nx$+sj',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = getenv("DJANGO_DEBUG", "0") == "1"
# DEBUG = True

ALLOWED_HOSTS = [
    "0.0.0.0",    # разрешаем подключение с любого интерфейса (для докера/сети)
    "127.0.0.1",  # разрешаем локальные подключения
] + getenv("DJANGO_ALLOWED_HOST", "").split(",")

INTERNAL_IPS = [
    "127.0.0.1",  # внутренние IP для дебага, например django-debug-toolbar

]

if DEBUG:
    import socket   # импортируем модуль для работы с сетевыми именами и IP
    hostname, __, ips = socket.gethostbyname_ex(socket.gethostname())
    # получаем имя текущей машины (hostname) и список её IP-адресов (ips)
    INTERNAL_IPS.append("10.0.2.2")
    INTERNAL_IPS.extend(
        [ip[: ip.rfind(".")] + ".1" for ip in ips]
    )

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',          # Админ-панель Django
    'django.contrib.auth',           # Система аутентификации и авторизации пользователей
    'django.contrib.contenttypes',   # Поддержка типов контента (связи между моделями)
    'django.contrib.sessions',       # Механизм сессий для хранения данных пользователей
    'django.contrib.messages',       # Система сообщений (flash-сообщения, уведомления)
    'django.contrib.staticfiles',    # Обработка статических файлов (CSS, JS, изображения)
    'django.contrib.admindocs',      # приложение документации Django, активирует /admin/doc/

    'rest_framework', # Django REST Framework — позволяет создавать API (эндпоинты, сериализация, JSON-ответы)
    'django_filters', # приложение для фильтрации данных в Django и DRF

    'drf_spectacular', # Генерация OpenAPI-спецификации и документации для DRF (Swagger / Redoc)

    'debug_toolbar',  # Профилирование и отладка прямо в браузере

    'shopapp.apps.ShopappConfig', # Приложение интернет-магазина
    'myauth.apps.MyauthConfig',   # Приложение для аутентификации
    'blogapp.apps.BlogappConfig',  # Приложение - Блог
    'new_blogapp_rss.apps.NewBlogappRssConfig', # приложение - новый блог rss https://ru.wikipedia.org/wiki/RSS
    'django.contrib.sitemaps', # приложение для генерации карты сайта

]

MIDDLEWARE = [
    # 'django.middleware.cache.UpdateCacheMiddleware', # Сохраняет готовый HTTP-ответ в кеш (per-site cache)-(пишет в кеш)
    'django.middleware.security.SecurityMiddleware', # Обеспечивает базовую безопасность (например, HTTPS и заголовки безопасности)
    'django.contrib.sessions.middleware.SessionMiddleware', # Включает поддержку сессий для пользователей
    'django.middleware.locale.LocaleMiddleware', # Выбирает язык для пользователя по cookie, URL или браузеру
    'django.middleware.common.CommonMiddleware', # Общие вещи: редиректы с /, обработка ETag и прочее
    'django.middleware.csrf.CsrfViewMiddleware', # Защита от CSRF-атак (подделка запросов)
    'django.contrib.auth.middleware.AuthenticationMiddleware', # Поддержка авторизации пользователей (request.user)
    'django.contrib.messages.middleware.MessageMiddleware', # Поддержка flash-сообщений (django.contrib.messages)
    'django.middleware.clickjacking.XFrameOptionsMiddleware', # Защита от clickjacking (запрет встраивания в iframe)
    'django.contrib.admindocs.middleware.XViewMiddleware', # поддержка admindocs, добавляет X-View заголовок
    'debug_toolbar.middleware.DebugToolbarMiddleware', # Middleware Debug Toolbar для профилирования и отладки
    # 'django.middleware.cache.FetchFromCacheMiddleware', # Пытается взять готовый HTTP-ответ из кеша до обработки запроса
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': DATABASE_DIR / 'db.sqlite3',
    }
}


CACHES = {  # Основная настройка системы кеширования Django
    "default": {  # Кеш по умолчанию, который будет использоваться Django
        "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
        # Тип кеша: файловый (данные кеша хранятся в файлах)

        "LOCATION": "/var/tmp/django_cache",
        # Путь к директории, где Django будет хранить файлы кеша
        # "BACKEND": "django.core.cache.backends.dummy.DummyCache", # Фековый кэш для отладки
    },
}

CACHE_MIDDLEWARE_SECONDS = 200 # Задаем время кеширования на 200 секунд

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us' # язык проекта по умолчанию

# LANGUAGE_CODE = 'ru' # временно переопределяем язык проекта на русский

TIME_ZONE = 'UTC'

USE_I18N = True # Это включает интернационализацию. Перевод (translation) управляется настройкой USE_I18N

USE_TZ = True

USE_L10N = True # Это включает локализацию форматов (даты, числа и т.п.)

LOCALE_PATHS = [
    BASE_DIR / 'locale'   # Папка, где Django будет хранить файлы перевода (.po и .mo) для проекта.
]

LANGUAGES = [
    ('en', _('English')),  # Доступный язык №1: код языка + отображаемое название с поддержкой перевода.
    ('ru', _('Russian')),  # Доступный язык №2: код языка + переведённое название языка.
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "blogapp" / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"


# URL, по которому будут доступны загруженные пользователями файлы в браузере
# Например, если пользователь загрузил avatar.png, его можно открыть по адресу:
# http://localhost:8000/media/avatar.png
MEDIA_URL = "/media/"

# Папка на диске, где реально будут храниться загруженные файлы
# BASE_DIR — это корень проекта (обычно папка с manage.py)
# 'uploads' — подпапка внутри корня проекта
# То есть полный путь на диске: /home/user/.../PythonProjectDjango/Files/uploads
MEDIA_ROOT = BASE_DIR / 'uploads'


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = reverse_lazy("myauth:about-my")
# Страница, на которую будет перенаправлен пользователь после успешного входа в систему (логина).

LOGIN_URL = reverse_lazy("myauth:login")
# URL страницы входа (логина), на которую перенаправляются неавторизованные пользователи при попытке доступа к защищённым страницам.

REST_FRAMEWORK = {
    # Класс для автоматической генерации OpenAPI-схемы (используется drf-spectacular)
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",

    # Включаем постраничную пагинацию по умолчанию (?page=1, ?page=2)
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",

    # Количество объектов на странице при пагинации
    "PAGE_SIZE": 10,

    # Поддержка фильтрации через django-filter (фильтры в DRF)
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend"
    ],
}

SPECTACULAR_SETTINGS = {
    # Заголовок API, отображается в Swagger/Redoc
    'TITLE': 'My Site Project API',

    # Описание API — краткое объяснение проекта
    'DESCRIPTION': 'My site with shop and custom auth',

    # Версия вашего API (можно менять при обновлениях)
    'VERSION': '1.0.0',

    # Убираем саму OpenAPI-схему из выдачи (обычно не нужна пользователям)
    'SERVE_INCLUDE_SCHEMA': False,
}




LOGFILE_NAME = BASE_DIR / "log.txt" # указываем куда писать логи(базовая директория, файл - log.txt)
LOGFILE_SIZE = 1 * 1024 * 1024 # указываем максимальный размер файла, по достижению которого произойдет ротация логов
LOGFILE_COUNT = 3 # указываем КОЛ-ВО файлов для ротаций 1 текущий 3 пред идущих

LOGLEVEL = getenv("DJANGO_LOGLEVEL", "info").upper()

LOGGING = {  # Основная настройка логирования Django, читается при старте проекта

    "version": 1,  # Версия схемы logging.dictConfig (в Django всегда 1)
    # False — не отключать встроенные логгеры Django (django.request, django.db и т.д.)
    # True — отключит все существующие логгеры (обычно НЕ нужно)
    "disable_existing_loggers": False,
    "formatters": { # Форматтеры определяют, КАК будет выглядеть лог-сообщение
        "verbose": { # Имя форматтера (Можно назвать как угодно (simple, default, prod))
            "format": "%(asctime)s [%(levelname)s] %(name)s: %(message)s",
            # asctime — дата и время записи лога
            # levelname — уровень лога (INFO, ERROR, ...)
            # name — имя логгера (например: shopapp.views)
            # message — текст сообщения
        },
    },
    "handlers": { # Handlers определяют, КУДА будут отправляться логи (обработчики)
        "console": { # Имя обработчика, будет использоваться в root
            "class": "logging.StreamHandler", # StreamHandler выводит логи в консоль (stdout)
            "formatter": "verbose", # Какой форматтер использовать для этого обработчика
        },
        "logfile": { # Имя обработчика, будет использоваться в root
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOGFILE_NAME, # указываем куда писать логи
            "maxBytes": LOGFILE_SIZE, # указываем максимальный размер файла, по достижению которого произойдет ротация
            "backupCount": LOGFILE_COUNT, # указываем КОЛ-ВО файлов для ротаций 1 текущий 3 пред идущих
            "formatter": "verbose", # Какой форматтер использовать для этого обработчика
        }
    },
    "root": {  # Корневой логгер — получает все логи,
        # если у логгера нет собственной настройки
        "handlers": ["console", "logfile"], # Все логи отправляются в обработчик console и logfile
        "level": LOGLEVEL,
        # Минимальный уровень логов:
        # INFO, WARNING, ERROR, CRITICAL — будут выведены
        # DEBUG — проигнорируется
    },
}
